import { describe, expect, it } from "vitest";

import { clarificationQuestionSchema, requirementAgentResponseSchema } from "@/lib/requirements/schemas";

describe("LLM requirement response schema", () => {
  it("requires model-generated answer options for clarification questions", () => {
    const parsed = clarificationQuestionSchema.parse({
      id: "q_business_type",
      question: "What type of business app are you building?",
      reason: "The business domain drives requirements.",
      target: "client",
      options: [
        { label: "Ecommerce", value: "The app is for ecommerce.", recommended: true },
        { label: "Healthcare", value: "The app is for healthcare." },
        { label: "Other", value: "I want to describe another business type." },
      ],
    });

    expect(parsed.options).toHaveLength(3);
  });

  it("accepts OpenAI as the only client-facing provider", () => {
    const parsed = requirementAgentResponseSchema.parse({
      projectId: "project-test",
      scenario: "initial_discovery",
      summary: "LLM-generated response.",
      questions: [],
      suggestions: [],
      requirements: [
        {
          id: "REQ-001",
          title: "LLM requirement",
          description: "The LLM shall generate requirement content.",
          acceptanceCriteria: ["The response is generated by OpenAI."],
          priority: "must_have",
        },
      ],
      artifacts: [
        {
          kind: "developer_srs",
          title: "Developer SRS",
          content: "# SRS",
          format: "markdown",
        },
      ],
      nextAction: "Review the generated output.",
      provider: "openai",
    });

    expect(parsed.provider).toBe("openai");
  });

  it("allows empty requirements during early LLM interview turns", () => {
    const parsed = requirementAgentResponseSchema.parse({
      projectId: "project-test",
      scenario: "initial_discovery",
      summary: "The LLM is still gathering client context.",
      questions: [
        {
          id: "q_business_type",
          question: "What type of business app are you building?",
          reason: "The business domain drives requirements.",
          target: "client",
          options: [
            { label: "Ecommerce", value: "ecommerce", recommended: true },
            { label: "Healthcare", value: "healthcare" },
            { label: "Other", value: "other" },
          ],
        },
      ],
      suggestions: [],
      requirements: [],
      artifacts: [
        {
          kind: "clarification_questions",
          title: "Clarification Questions",
          content: "What type of business app are you building?",
          format: "markdown",
        },
      ],
      nextAction: "Answer the next interview question.",
      provider: "openai",
    });

    expect(parsed.requirements).toEqual([]);
  });
});
